[platformio]
default_envs = tdeck
boards_dir = boards

[env:tdeck]
platform = espressif32@6.3.0
board = T-Deck
framework = arduino
upload_speed = 921600
monitor_speed = 115200

lib_deps =
  jgromes/RadioLib@^7.1.2
  moononournation/GFX Library for Arduino@1.4.7
  https://github.com/lewisxhe/SensorLib.git
  h2zero/NimBLE-Arduino@^2.3.6

build_flags =
  -DBOARD_HAS_PSRAM=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DDISABLE_ALL_LIBRARY_WARNINGS
  -DRADIOLIB_EXCLUDE_CC1101
  -DRADIOLIB_EXCLUDE_NRF24
  -DRADIOLIB_EXCLUDE_RF69
  -DRADIOLIB_EXCLUDE_SX1231
  -DRADIOLIB_EXCLUDE_SI443X
  -DRADIOLIB_EXCLUDE_RFM2X
  -DRADIOLIB_EXCLUDE_SX127X
  -DRADIOLIB_EXCLUDE_SX128X
  -DRADIOLIB_EXCLUDE_AFSK
  -DRADIOLIB_EXCLUDE_AX25
  -DRADIOLIB_EXCLUDE_APRS
  -DRADIOLIB_EXCLUDE_BELL
  -DRADIO_FREQ_MHZ=915.0
  -DCHAT_MAX_RETRIES=8
  -DCHAT_ACK_TIMEOUT_MS=2500
  -DENABLE_BLE_MESH=0
  -DENABLE_FREQ_HOPPING=1

[env:heltec_v3]
platform = espressif32@6.3.0
board = heltec_wifi_lora_32_V3
framework = arduino
upload_speed = 460800
monitor_speed = 115200

lib_deps =
  jgromes/RadioLib@^7.1.2
  adafruit/Adafruit GFX Library@^1.11.11
  adafruit/Adafruit SSD1306@^2.5.13
  h2zero/NimBLE-Arduino@^2.3.6

build_flags =
  -DBOARD_HELTEC_V3=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DDISABLE_ALL_LIBRARY_WARNINGS
  -DRADIOLIB_EXCLUDE_CC1101
  -DRADIOLIB_EXCLUDE_NRF24
  -DRADIOLIB_EXCLUDE_RF69
  -DRADIOLIB_EXCLUDE_SX1231
  -DRADIOLIB_EXCLUDE_SI443X
  -DRADIOLIB_EXCLUDE_RFM2X
  -DRADIOLIB_EXCLUDE_SX127X
  -DRADIOLIB_EXCLUDE_SX128X
  -DRADIOLIB_EXCLUDE_AFSK
  -DRADIOLIB_EXCLUDE_AX25
  -DRADIOLIB_EXCLUDE_APRS
  -DRADIOLIB_EXCLUDE_BELL
  -DRADIO_FREQ_MHZ=915.0
  -DCHAT_MAX_RETRIES=8
  -DCHAT_ACK_TIMEOUT_MS=2500
  -DENABLE_BLE_MESH=0